-- MUBASHER_LSF.VW_L08_SYMBOL_BASE source

CREATE OR REPLACE FORCE VIEW "MUBASHER_LSF"."VW_L08_SYMBOL_BASE" ("L08_SYMBOL_CODE", "L08_EXCHANGE", "L08_SHORT_DESC", "L08_PREVIOUS_CLOSED", "L08_AVAILABLE_QTY", "L08_MARKET_VALUE", "L08_L10_LIQUID_ID", "L08_ALLOWED_FOR_COLLATERAL", "L08_LTP", "L08_SHORT_DESC_AR", "L08_CONCENTRATION_TYPE", "L08_INSTRUMENT_TYPE", "L08_SECURITY_TYPE", "L08_ALLOWED_FOR_PO") AS 
  SELECT base."L08_SYMBOL_CODE",base."L08_EXCHANGE",base."L08_SHORT_DESC",base."L08_PREVIOUS_CLOSED",base."L08_AVAILABLE_QTY",base."L08_MARKET_VALUE",base."L08_L10_LIQUID_ID",base."L08_ALLOWED_FOR_COLLATERAL",base."L08_LTP",base."L08_SHORT_DESC_AR",base."L08_CONCENTRATION_TYPE",base."L08_INSTRUMENT_TYPE",base."L08_SECURITY_TYPE",base."L08_ALLOWED_FOR_PO" 
FROM L08_SYMBOL base
WHERE base.L08_SYMBOL_CODE NOT LIKE '%.%'
  AND base.L08_SYMBOL_CODE NOT LIKE '%`O'
  AND base.L08_SYMBOL_CODE NOT LIKE '%`B'
 -- AND EXISTS (
  --  SELECT 1
  --  FROM L08_SYMBOL variant
  --  WHERE variant.L08_SYMBOL_CODE LIKE base.L08_SYMBOL_CODE || '.%'
  --     OR variant.L08_SYMBOL_CODE = base.L08_SYMBOL_CODE || '`O'
 -- )
  AND base.L08_INSTRUMENT_TYPE IN (0,86,75);