spring:
  application:
    name: lsf-server
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: lsf
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

# Integration service configuration
integration:
  # Connection timeouts in milliseconds
  connection:
    timeout: 5000
  read:
    timeout: 60000
  write:
    timeout: 5000
  # Default timeout for requests
  timeout: 60000
  # Maximum size of in-memory buffer for responses
  max-in-memory-size: 16777216  # 16MB
  
  # Service base URLs
  oms:
    base-url: http://localhost:8080/oms/api
  notification:
    base-url: http://localhost:8080/notification/api
  iflex:
    base-url: http://localhost:8080/iflex/api

# Logging configuration
logging:
  level:
    root: INFO
    com.dfn.lsf: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG