DECLARE
    l_count   NUMBER := 0;
    l_ddl     VARCHAR2 (1000)
        := 'ALTER TABLE L08_SYMBOL ADD(L08_INSTRUMENT_TYPE NUMBER (3, 0))';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM all_tab_columns
     WHERE     owner = UPPER ('MUBASHER_LSF')
           AND table_name = UPPER ('L08_SYMBOL')
           AND column_name = UPPER ('L08_INSTRUMENT_TYPE');

    IF l_count = 0
    THEN
        EXECUTE IMMEDIATE l_ddl;
    END IF;
END;
/

DECLARE
    l_count   NUMBER := 0;
    l_ddl     VARCHAR2 (1000)
        := 'ALTER TABLE L08_SYMBOL ADD(L08_SECURITY_TYPE VARCHAR (100))';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM all_tab_columns
     WHERE     owner = UPPER ('MUBASHER_LSF')
           AND table_name = UPPER ('L08_SYMBOL')
           AND column_name = UPPER ('L08_SECURITY_TYPE');

    IF l_count = 0
    THEN
        EXECUTE IMMEDIATE l_ddl;
    END IF;
END;
/

DECLARE
    l_count   NUMBER := 0;
    l_ddl     VARCHAR2 (1000)
        := 'ALTER TABLE L08_SYMBOL ADD(L08_ALLOWED_FOR_PO NUMBER(38,0) DEFAULT 0 NULL)';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM all_tab_columns
     WHERE     owner = UPPER ('MUBASHER_LSF')
           AND table_name = UPPER ('L08_SYMBOL')
           AND column_name = UPPER ('L08_ALLOWED_FOR_PO');

    IF l_count = 0
    THEN
        EXECUTE IMMEDIATE l_ddl;
    END IF;
END;
/

--CREATE TABLE TEMP_L08_SYMBOL AS
--SELECT * FROM MUBASHER_LSF.L08_SYMBOL WHERE 1=0;

--INSERT INTO TEMP_L08_SYMBOL
--SELECT * FROM MUBASHER_LSF.L08_SYMBOL;

--SELECT COUNT(*)  FROM TEMP_L08_SYMBOL;

--ALTER TABLE MUBASHER_LSF.L35_SYMBOL_MARGINABILITY_PERC DROP CONSTRAINT L08_SYMBOL_SYMBOL_EXCHANGE_FK;

--ALTER TABLE MUBASHER_LSF.L09_TRADING_SYMBOLS DROP CONSTRAINT R_9;
--ALTER TABLE MUBASHER_LSF.L16_PURCHASE_ORDER_SYMBOL DROP CONSTRAINT R_20_16;
--ALTER TABLE MUBASHER_LSF.L13_SYMBOL_WISHLIST DROP CONSTRAINT R_19;


--DELETE FROM MUBASHER_LSF.L08_SYMBOL;

ALTER TABLE MUBASHER_LSF.L08_SYMBOL MODIFY L08_SHORT_DESC VARCHAR2(2000);
/
ALTER TABLE MUBASHER_LSF.L08_SYMBOL MODIFY L08_SHORT_DESC_AR VARCHAR2(4000);
/
