CREATE TABLE CUSTOMER_INFO_SYNC (
      CUSTOMER_ID VARCHAR2(50) PRIMARY KEY,
      NAME_IN_FULL VARCHAR2(200),
      OCCUPATION VARCHAR2(100),
      EMPLOYEER VARCHAR2(200),
      AVG_MONTHLY_INCOME NUMBER(15,2),
      EMAIL VARCHAR2(100),
      ADDRESS VARCHAR2(500),
      MOBILE_NO VARCHAR2(20),
      TELEPHONE_NO VARCHAR2(20),
      FAX VARCHAR2(20),
      CUSTOMER_REFERENCE_NUMBER VARCHAR2(50),
      ZIP_CODE VARCHAR2(10),
      BANK_BRANCH_NAME VARCHAR2(200),
      CITY VARCHAR2(100),
      PO_BOX VARCHAR2(50),
      PREFERED_LANGUAGE CHAR(1),
      EMPLOYER_ADRS VARCHAR2(500),
      NET_WORTH VARCHAR2(50),
      INVEST_EXPRNC VARCHAR2(50),
      RISK_APPETITE VARCHAR2(50),
      KYC_EXPIRY_DATE VARCHAR2(20),
      HOME_TELEPHONE VARCHAR2(20),
      NIN VARCHAR2(50),
      CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );


DECLARE
    l_count   NUMBER := 0;
    l_ddl     VARCHAR2 (1000)
        := 'ALTER TABLE CUSTOMER_INFO_SYNC ADD(NATIONALITY VARCHAR2(100))';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM all_tab_columns
     WHERE     owner = UPPER ('MUBASHER_LSF')
           AND table_name = UPPER ('CUSTOMER_INFO_SYNC')
           AND column_name = UPPER ('NATIONALITY');

    IF l_count = 0
    THEN
        EXECUTE IMMEDIATE l_ddl;
    END IF;
END;
/

DECLARE
    l_count   NUMBER := 0;
    l_ddl     VARCHAR2 (1000)
        := 'ALTER TABLE CUSTOMER_INFO_SYNC ADD(BIRTH_DATE VARCHAR2(50))';
BEGIN
    SELECT COUNT (*)
      INTO l_count
      FROM all_tab_columns
     WHERE     owner = UPPER ('MUBASHER_LSF')
           AND table_name = UPPER ('CUSTOMER_INFO_SYNC')
           AND column_name = UPPER ('BIRTH_DATE');

    IF l_count = 0
    THEN
        EXECUTE IMMEDIATE l_ddl;
    END IF;
END;
/